<?php
/**
 * JS Helper init
 *
 * @var $block \Magento\Framework\View\Element\Template
 * @var $helper \Boxalino\RealTimeUserExperience\Helper\Js\Configuration
 */
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
?>
<?php
$helper = $this->helper(\Boxalino\RealTimeUserExperience\Helper\Js\Configuration::class);
?>
<?php if($helper->isTrackerActive()):?>
    <script type="text/javascript">
        window._bxq = window._bxq || [];
        function bxq(arguments) { _bxq.push(arguments); }
        <?php if($helper->isTrackingRestricted() && $helper->userNotAllowedSaveCookie()): ?>
        _bxq.push(['setOptions', {'requireOptIn': true}]);
        <?php endif;?>
        bxq(['setAccount', "<?= $block->escapeHtml($helper->getAccount()) ?>"]);
        bxq(['trackPageView']);
    </script>
    <script async src="<?= $block->escapeHtml($helper->getTrackerUrl()) ?>"></script>
    <?php if($helper->isRtiActive()):?>
        <script async src="<?= $block->escapeHtml($helper->getRtiUrl()) ?>"></script>
    <?php endif; ?>
    <script type="text/x-magento-init">
        {
            "*":{
                "rtuxApiHelper": {
                    "account":"<?= $block->escapeHtml($helper->getAccount()) ?>",
                    "key":"<?= $block->escapeHtml($helper->getKey()) ?>",
                    "endpoint":"<?= $block->escapeHtml($helper->getEndpoint()) ?>",
                    "language":"<?= $block->escapeHtml($helper->getLanguage()) ?>",
                    "dev":<?= json_encode($helper->isDev()) ?>,
                    "test":<?= json_encode($helper->isTest()) ?>,
                    "isRestricted": <?= json_encode($helper->isTrackingRestricted()) ?>,
                    "isUserNotAllowed": <?= json_encode($helper->userNotAllowedSaveCookie()) ?>,
                    "isNavigation": <?= json_encode($this->getRequest()->getModuleName() ==='catalog' && $this->getRequest()->getControllerName() ==='category' && $this->getRequest()->getActionName() ==='view'); ?>,
                    "isSearch": <?= json_encode($this->getRequest()->getModuleName() ==='catalogsearch' && $this->getRequest()->getControllerName() ==='result' && $this->getRequest()->getActionName() ==='index'); ?>,
                    "isProduct": <?= json_encode($this->getRequest()->getModuleName() ==='catalog' && $this->getRequest()->getControllerName() ==='product' && $this->getRequest()->getActionName() ==='view'); ?>,
                    "activeId": <?= json_encode($this->getRequest()->getParam("id")); ?>,
                    "currencyCode": "<?= $helper->getCurrencyCode(); ?>",
                    "active" : <?= json_encode($helper->getSessionAttributes()) ?>
        }
    }
}
    </script>
<?php endif;?>
