<?php
/**
 * JS Tracker init
 *
 * @var $block \Magento\Framework\View\Element\Template
 * @var $helper \Boxalino\RealTimeUserExperience\Helper\Js\Configuration
 */
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
?>
<?php
$helper = $this->helper(\Boxalino\RealTimeUserExperience\Helper\Js\Configuration::class);
?>
<script>
     window._bxq = window._bxq || [];
     function bxq(arguments) { _bxq.push(arguments); }
</script>
<script type="text/x-magento-init">
    {
        "*": {
            "Boxalino_RealTimeUserExperience/js/rtuxApiTracker": {
                "isRestricted": <?= json_encode($helper->isTrackingRestricted()) ?>,
                "moduleName": "<?= $this->getRequest()->getModuleName(); ?>",
                "controllerName": "<?= $this->getRequest()->getControllerName(); ?>",
                "actionName": "<?= $this->getRequest()->getActionName(); ?>",
                "activeId": <?= json_encode($this->getRequest()->getParam("id")); ?>,
                "currencyCode": "<?= $helper->getCurrencyCode(); ?>"
            }
        }
    }
</script>
